#Store that is common in all module
org = "Ajmerainfotech"
project = "Aj_Pj-An_CC-AS87"
project_prefix = "Assetronai"
environment = "prod"
environment_version = "100"
state_resource_group_name   = "assetronai-dev-100-rg-102"
state_storage_account_name  = "sa0999"
state_container_name        = "sacon100"
state_key                   = "state100.tfstate"
state_access_key            = "5v9vr4gJni1vbH7o/oNXXv5ocKtKeuenr/1kr27aRTjUQWb6LKfpHAszwILleSSAZTlqgEt8A60v+ASteZYaIw=="
