name:  inqa_onpush_byqaplanapply

on:
  push:
    branches:
      - qa
      - 'feature_qa_*'
    paths:
      - '.github/workflows/inqa_onpush_byqaplanapply.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  WORKING_DIR: .
  TF_VER: 1.1.0
  BACKEND_FILE: provider.tf

jobs:
  tf-plan:
    name: 'terraform: init,validate,plan'
    
    timeout-minutes: 5

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    environment: qa_plan

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_QA_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_QA_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_QA_CLIENT_SECRET }}

    steps:
      - run: echo inqa_onpush_byqaplanapply
