name:  indev_onpush_bydevplanapply

on:
  push:
    branches:
      - dev
      - 'feature_dev_*'
      - qa
      - 'feature_qa_*'
      - prod

    paths:
      - '.github/workflows/onpush_planapply.yml'

  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

env:
  WORKING_DIR: .
  TF_VER: 1.1.0
  BACKEND_FILE: backend.tfvars
  JOB_TIMEOUT_MINUTES_LONG_HERE: 5

jobs:
  tf-plan-dev:
    environment: dev_plan

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_DEV_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_DEV_CLIENT_SECRET }}
      STATE_RESOURCE_GROUP_NAME: ${{ secrets.STATE_DEV_RESOURCE_GROUP_NAME }}
      STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.STATE_DEV_STORAGE_ACCOUNT_NAME }}
      STATE_CONTAINER_NAME: ${{ secrets.STATE_DEV_CONTAINER_NAME }}
      STATE_KEY: ${{ secrets.STATE_DEV_KEY }}
      STATE_ACCESS_KEY: ${{ secrets.STATE_DEV_ACCESS_KEY }}
      JOB_TIMEOUT_MINUTES_LONG: $JOB_TIMEOUT_MINUTES_LONG

    name: 'tf-plan-dev: init,validate,plan'
    
    timeout-minutes: ${{env.JOB_TIMEOUT_MINUTES_LONG }}

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature_dev') || github.ref == 'refs/heads/dev'

    defaults:
      run:
        shell: bash
        working-directory: .


    steps:
      - run: echo onpush_planapply
      - run: echo "${{ secrets.AZURE_DEV_CLIENT_ID }}"
      - run: echo ${{ secrets.AZURE_DEV_CLIENT_ID }}
      - run: echo "$STATE_DEV_ACCESS_KEY"
      - run: echo $STATE_DEV_ACCESS_KEY
      - run: echo "$JOB_TIMEOUT_MINUTES_LONG"
      - run: echo $JOB_TIMEOUT_MINUTES_LONG

      - uses: actions/checkout@v3

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: Azure Login
        run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Azure CLI Command
        run: az account show

      - name: Run> terraform init
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform init -upgrade -input=false -reconfigure

      # - name: Run> terraform init
      #   run: |
      #     cd "${{ env.WORKING_DIR}}"
      #     terraform init -upgrade -input=false -reconfigure -backend-config="${{ env.CONFIG_DIR }}/${{ env.BACKEND_FILE }}"

      # - name: Run> terraform init
      #   run: |
      #     cd "${{ env.WORKING_DIR}}"
      #     terraform init -upgrade -input=false -reconfigure\
      #        -backend-config "state_resource_group_name=$STATE_DEV_RESOURCE_GROUP_NAME" \ 
      #        -backend-config "state_storage_account_name=$STATE_DEV_STORAGE_ACCOUNT_NAME" \ 
      #        -backend-config "state_container_name=$STATE_DEV_CONTAINER_NAME" \ 
      #        -backend-config "state_key=$TSTATE_DEV_KEY"
      #        -backend-config "state_access_key=$STATE_DEV_ACCESS_KEY"

      - name: Run> terraform validate
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform validate

      - name: Run> terraform plan
        id: tf-plan
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform plan -detailed-exitcode -input=false
        continue-on-error: true

      - name: Check for "terraform plan" failure
        if: steps.tf-plan-dev.outputs.exitcode == 1
        run: exit 1

    outputs:
      tf-plan-exit-code: ${{ steps.tf-plan-dev.outputs.exitcode }}

  tf-apply-dev:
    name: 'tf-plan-dev: apply'
    
    timeout-minutes: 5

    runs-on: ubuntu-latest
    needs: tf-plan-dev
    if: |
      needs.tf-plan-dev.outputs.tf-plan-exit-code == 2 && (startsWith(github.ref, 'refs/heads/feature_dev') || github.ref == 'refs/heads/dev')

    defaults:
      run:
        shell: bash
        working-directory: .

    environment: dev_planapply

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_DEV_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_DEV_CLIENT_SECRET }}
      STATE_RESOURCE_GROUP_NAME: ${{ secrets.STATE_DEV_RESOURCE_GROUP_NAME }}
      STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.STATE_DEV_STORAGE_ACCOUNT_NAME }}
      STATE_CONTAINER_NAME: ${{ secrets.STATE_DEV_CONTAINER_NAME }}
      STATE_KEY: ${{ secrets.STATE_DEV_KEY }}
      STATE_ACCESS_KEY: ${{ secrets.STATE_DEV_ACCESS_KEY }}

    steps:
      - run: echo onpush_planapply
  
      - uses: actions/checkout@v3

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: Azure Login
        run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Azure CLI Command
        run: az account show

      - name: Run> terraform init
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform init -upgrade -input=false -reconfigure -backend-config="${{ env.CONFIG_DIR }}/${{ env.BACKEND_FILE }}"

      - name: Run> terraform validate
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform validate

      - name: Run> terraform fmt
        run: |
          cd "${{ env.WORKING_DIR }}"
          terraform fmt -check -recursive
        continue-on-error: true

      - name: Run> terraform apply
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform apply -auto-approve

  tf-plan-qa:
    name: 'tf-plan-qa: init,validate,plan'
    
    timeout-minutes: 5

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature_qa') || github.ref == 'refs/heads/qa'

    defaults:
      run:
        shell: bash
        working-directory: .

    environment: qa_plan

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_QA_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_QA_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_QA_CLIENT_SECRET }}
      STATE_RESOURCE_GROUP_NAME: ${{ secrets.STATE_QA_RESOURCE_GROUP_NAME }}
      STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.STATE_QA_STORAGE_ACCOUNT_NAME }}
      STATE_CONTAINER_NAME: ${{ secrets.STATE_QA_CONTAINER_NAME }}
      STATE_KEY: ${{ secrets.STATE_QA_KEY }}
      STATE_ACCESS_KEY: ${{ secrets.STATE_QA_ACCESS_KEY }}

    steps:
      - run: echo onpush_planapply

      - uses: actions/checkout@v3

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: Azure Login
        run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Azure CLI Command
        run: az account show

      - name: Run> terraform init
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform init -upgrade -input=false -reconfigure -backend-config="${{ env.CONFIG_DIR }}/${{ env.BACKEND_FILE }}"

      - name: Run> terraform validate
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform validate

      - name: Run> terraform plan
        id: tf-plan
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform plan -detailed-exitcode -input=false
        continue-on-error: true

      - name: Check for "terraform plan" failure
        if: steps.tf-plan-qa.outputs.exitcode == 1
        run: exit 1

    outputs:
      tf-plan-exit-code: ${{ steps.tf-plan-qa.outputs.exitcode }}

  tf-apply-qa:
    name: 'tf-plan-qa: apply'
    
    timeout-minutes: 5

    runs-on: ubuntu-latest
    needs: tf-plan-qa
    if: |
      needs.tf-plan-qa.outputs.tf-plan-exit-code == 2 && (startsWith(github.ref, 'refs/heads/feature_qa') || github.ref == 'refs/heads/qa')

    defaults:
      run:
        shell: bash
        working-directory: .

    environment: qa_planapply

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_QA_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_QA_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_QA_CLIENT_SECRET }}
      STATE_RESOURCE_GROUP_NAME: ${{ secrets.STATE_QA_RESOURCE_GROUP_NAME }}
      STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.STATE_QA_STORAGE_ACCOUNT_NAME }}
      STATE_CONTAINER_NAME: ${{ secrets.STATE_QA_CONTAINER_NAME }}
      STATE_KEY: ${{ secrets.STATE_QA_KEY }}
      STATE_ACCESS_KEY: ${{ secrets.STATE_QA_ACCESS_KEY }}

    steps:
      - run: echo onpush_planapply
  
      - uses: actions/checkout@v3

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: Azure Login
        run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Azure CLI Command
        run: az account show

      - name: Run> terraform init
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform init -upgrade -input=false -reconfigure -backend-config="${{ env.CONFIG_DIR }}/${{ env.BACKEND_FILE }}"

      - name: Run> terraform validate
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform validate

      - name: Run> terraform fmt
        run: |
          cd "${{ env.WORKING_DIR }}"
          terraform fmt -check -recursive
        continue-on-error: true

      - name: Run> terraform apply
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform apply -auto-approve

  tf-plan-prod:
    name: 'tf-plan-prod: init,validate,plan'
    
    timeout-minutes: 5

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    defaults:
      run:
        shell: bash
        working-directory: .

    environment: prod_plan

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_PROD_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_PROD_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_PROD_CLIENT_SECRET }}
      STATE_RESOURCE_GROUP_NAME: ${{ secrets.STATE_PROD_RESOURCE_GROUP_NAME }}
      STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.STATE_PROD_STORAGE_ACCOUNT_NAME }}
      STATE_CONTAINER_NAME: ${{ secrets.STATE_PROD_CONTAINER_NAME }}
      STATE_KEY: ${{ secrets.STATE_PROD_KEY }}
      STATE_ACCESS_KEY: ${{ secrets.STATE_PROD_ACCESS_KEY }}

    steps:
      - run: echo onpush_planapply

      - uses: actions/checkout@v3

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: Azure Login
        run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Azure CLI Command
        run: az account show

      - name: Run> terraform init
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform init -upgrade -input=false -reconfigure -backend-config="${{ env.CONFIG_DIR }}/${{ env.BACKEND_FILE }}"

      - name: Run> terraform validate
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform validate

      - name: Run> terraform plan
        id: tf-plan
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform plan -detailed-exitcode -input=false
        continue-on-error: true

      - name: Check for "terraform plan" failure
        if: steps.tf-plan-qa.outputs.exitcode == 1
        run: exit 1

    outputs:
      tf-plan-exit-code: ${{ steps.tf-plan-qa.outputs.exitcode }}

  tf-apply-prod:
    name: 'tf-plan-prod: apply'
    
    timeout-minutes: 5

    runs-on: ubuntu-latest
    needs: tf-plan-prod
    if: |
      needs.tf-plan-prod.outputs.tf-plan-exit-code == 2 && github.ref == 'refs/heads/prod'


    defaults:
      run:
        shell: bash
        working-directory: .

    environment: prod_planapply

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_PROD_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_PROD_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_PROD_CLIENT_SECRET }}
      STATE_RESOURCE_GROUP_NAME: ${{ secrets.STATE_PROD_RESOURCE_GROUP_NAME }}
      STATE_STORAGE_ACCOUNT_NAME: ${{ secrets.STATE_PROD_STORAGE_ACCOUNT_NAME }}
      STATE_CONTAINER_NAME: ${{ secrets.STATE_PROD_CONTAINER_NAME }}
      STATE_KEY: ${{ secrets.STATE_PROD_KEY }}
      STATE_ACCESS_KEY: ${{ secrets.STATE_PROD_ACCESS_KEY }}

    steps:
      - run: echo onpush_planapply
  
      - uses: actions/checkout@v3

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: Azure Login
        run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Azure CLI Command
        run: az account show

      - name: Run> terraform init
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform init -upgrade -input=false -reconfigure -backend-config="${{ env.CONFIG_DIR }}/${{ env.BACKEND_FILE }}"

      - name: Run> terraform validate
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform validate

      - name: Run> terraform fmt
        run: |
          cd "${{ env.WORKING_DIR }}"
          terraform fmt -check -recursive
        continue-on-error: true

      - name: Run> terraform apply
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform apply -auto-approve