name: Terraform Plan and Apply

on:
  push:
    branches:
      - dev
      - 'feature_dev_*'
    paths:
      - '.github/workflows/tf_dev_planapply_onpush.yml'

  workflow_dispatch:

jobs:
  tf-plan:
    name: 'terraform: init,validate,plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    environment: dev_planapply
      
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
