name: Terraform Plan and Apply

on:
  push:
    branches:
      - dev
      # - feature_dev_103SetWorkflow
      - 'feature_dev_*'

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  resourcegroups:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: 'Terraform Plan and Apply'

    # environment: dev_planapply
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_DEV_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_DEV_TENANT_ID }}
      
    steps:
      - uses: actions/checkout@v3

      - name: 'Terraform init'
        id: init
        run: terraform init

      - name: 'Terraform validate'
        id: validate
        run: terraform validate

      - name: 'Terraform plan'
        id: plan
        # run: terraform plan
        run: terraform plan -detailed-exitcode -input=false
        continue-on-error: true

      - name: Check for "terraform plan" failure
        if: steps.tf-plan.outputs.exitcode == 1
        run: exit 1

      - name: 'Terraform apply'
        id: apply
        run: terraform apply -auto-approve
