# name: tf_dev_planapply_onpush

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - dev
#       - 'feature_dev_*'
#     paths:
#       - '.github/workflows/tf_dev_planapply_onpush.yml'

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   tf-plan:
#     timeout-minutes: ${{ fromJSON(1) }}
#     name: 'terraform: init,validate,plan'
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash

#     environment: dev_plan

#     # env:
#     #   ARM_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
#     #   ARM_CLIENT_SECRET: ${{ secrets.AZURE_DEV_CLIENT_SECRET }}
#     #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
#     #   ARM_TENANT_ID: ${{ secrets.AZURE_DEV_TENANT_ID }}
      
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       - name: Install Azure cli
#         run: |
#           sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
#           curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
#           AZ_REPO=$(lsb_release -cs)
#           echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
#           sudo apt-get update
#           sudo apt-get install azure-cli

#       # - uses: azure/CLI@v1
#       #   with:
#       #     azcliversion: 2.0.72
#       #     inlineScript: |
#       #       az account list
            
#       # Log into Azure with OIDC integration if branch is main
#       - name: 'Az CLI login' 
#         uses: azure/login@v1
#         with:
#             client-id: ${{ secrets.AZURE_DEV_CLIENT_ID }}
#             tenant-id: ${{ secrets.AZURE_DEV_TENANT_ID }}
#             subscription-id: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}


#       # Runs a single command using the runners shell
#       - name: 'Terraform init'
#         id: init
#         env:
#             ARM_CLIENT_ID: ${{ secrets.AZURE_DEV_CLIENT_ID }}
#             ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_DEV_SUBSCRIPTION_ID }}
#             ARM_TENANT_ID: ${{ secrets.AZURE_DEV_TENANT_ID }}
#         run: terraform init -upgrade -input=false

#       - name: 'Terraform plan'
#         id: plan
#         run: terraform plan
          
#     outputs:
#       tf-plan-exit-code: ${{ steps.tf-plan.outputs.exitcode }}
