# name: Terraform Plan and Apply

# on:
#   pull_request:
#     types: [reopened, opened, synchronize, edited]
#     branches:
#       - dev
#     paths:
#       - '.github/workflows/tf_dev_planapply_onpr.yml'

#   workflow_dispatch:

# jobs:
#   tf-plan:
#     name: 'terraform: init,validate,plan'
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash

#     environment: dev_plan
      
#     steps:
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - uses: actions/checkout@v3

#       - name: Set git credential for private TF module access
#         run: |
#           git config --local --remove-section http."https://github.com/"
#           git config --global url."https://foo:${GH_REPO_ACCESS_PAT}@github.com/tandemdiabetes".insteadOf "https://github.com/tandemdiabetes"

#       - name: 'Terraform init'
#         id: init
#         run: terraform init -upgrade -input=false

#       - name: 'Terraform validate'
#         id: validate
#         run: terraform validate

#       - name: 'Terraform plan'
#         id: plan
#         run: terraform plan -detailed-exitcode -input=false
#         continue-on-error: true

#       - name: Check for "terraform plan" failure
#         if: steps.tf-plan.outputs.exitcode == 1
#         run: exit 1

#     outputs:
#       tf-plan-exit-code: ${{ steps.tf-plan.outputs.exitcode }}