name:  tf_Indev_1Onpush_009Doecho_2Bydevplanapply

on:
  push:
    branches:
      - dev
      - 'feature_dev_*'
    paths:
      - '.github/workflows/tf_Indev_1Onpush_009Doecho_2Bydevplanapply.yml'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  WORKING_DIR: .
  TF_VER: 1.1.0
  BACKEND_FILE: provider.tf

jobs:
  tf-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    environment: qa_planapply

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_QA_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_QA_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_QA_CLIENT_SECRET }}

    steps:
      - run: echo tf_Indev_1Onpush_009Doecho_2Bydevplanapply
  
      - run: echo ${{ secrets.AZURE_QA_CLIENT_ID }}

      - uses: actions/checkout@v3

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '${{ env.TF_VER }}'

      - name: Azure Login
        run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

      - name: Azure CLI Command
        run: az account show

      # - name: 'Terraform init'
      #   id: init
      #   run: terraform init -upgrade -input=false

      # - name: 'Terraform plan'
      #   id: plan
      #   run: terraform plan

      - name: Run> terraform init
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform init -upgrade -input=false -reconfigure"

      - name: Run> terraform validate
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform validate

      - name: Run> terraform plan
        id: tf-plan
        run: |
          cd "${{ env.WORKING_DIR}}"
          terraform plan -detailed-exitcode -input=false
        continue-on-error: true

      - name: Check for "terraform plan" failure
        if: steps.tf-plan.outputs.exitcode == 1
        run: exit 1

    outputs:
      tf-plan-exit-code: ${{ steps.tf-plan.outputs.exitcode }}
