name:  tf_Indev_1Onpush_001Doecho_1Bydevplan

on:
  push:
    branches:
      - dev
      - 'feature_dev_*'
    paths:
      - '.github/workflows/tf_Indev_1Onpush_001Doecho_1Bydevplan.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  WORKING_DIR: .
  TF_VER: 1.1.0
  BACKEND_FILE: provider.tf

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    environment: dev_planapply
    steps:
      - run: echo tf_Indev_1Onpush_001Doecho_1Bydevplan      
      -  run: |
          echo "Git Branch: $GITHUB_REF"